# Generated by Django 3.2.3 on 2021-05-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=34)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=34)),
                ('tel', models.CharField(max_length=30)),
                ('addr', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('birth', models.DateTimeField()),
            ],
        ),
    ]
